### ISSUE TITLE
Local Like Count Doesn't Match Backend

### ISSUE THREAD

**Issue by StacL** [UNLV-CS472-672/2024-S-GROUP5-Munch#116]
**Describe the bug**
A clear and concise description of what the bug is. Include what is expected and what is happening currently.

**To Reproduce**

1. Log into first account
2. create 2+ posts
8. go to own profile
9. like a post
10. notice that all the posts are updated with a like count
11. make a second account
12. create 2+ posts
13. follow the first account you created
14. like their posts
15. notice the like count can get messed up

**Screenshots**
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP5-Munch/assets/65695808/cbd0f101-4bec-435a-a205-8f65fbb74d18)

**Comment by StacL** [comment]
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP5-Munch/assets/65695808/bb38c784-a25d-4286-babe-53d4f0f03a78)

**Comment by mitshelle** [comment]
Closed with PR: https://github.com/UNLV-CS472-672/2024-S-GROUP5-Munch/pull/111
