### ISSUE TITLE
Add Creation Date to Follows and Likes

### ISSUE THREAD

**Issue by rparker2003** [UNLV-CS472-672/2024-S-GROUP5-Munch#87]
**Is your feature request related to a problem? Please describe.**
The front end needs a date for when someone followed and when someone liked. The routes need to be modified to adjust for the new schema below.
![](https://imgur.com/wzHGKB7.png)
![](https://imgur.com/bhbOfgm.png)

**Describe the solution you'd like**
Modify the follow and like routes to include a timestamp of when the action occurred. 
Possibly need to update the user routes as well to account for new changes to the user collection, as well as the user and recipe routes to account for new changes to the recipe and post collection.
Also need to modify the tests for all routes that are being changed and verify all pass.

**Describe alternatives you've considered**
None. Must be fixed.

**Comment by KeenParchment** [comment]
**Progress update:**
@Fabrizv and I are still working on this issue.
Currently, we have user route and post route working, as well as like/unlike route. We are testing it on the emulator and ensuring it works.
Follow route is still in progress, and test coverage for user routes and post routes needs to be reviewed for test coverage.

**Comment by mitshelle** [comment]
Closed with https://github.com/UNLV-CS472-672/2024-S-GROUP5-Munch/pull/100
